### PR TITLE
7902982: jcstress: Add samples for some mutex algorithms

### PR DESCRIPTION
**Pull request by mmirwaldt**
I have implemented 3 more samples:
*) the NoAlgorithm sample should show users of JCStress how they can define a critical section in a simple way
*) one sample for the Peterson's algorithm 
*) one sample for the Dekker's algorithm 
I have translated the pseudo code implementations of the English wikipedia articles to Java.
I have also tried out those examples: they compile and they run without any problems.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Change must be properly reviewed

### Issue
 * [CODETOOLS-7902982](https://bugs.openjdk.java.net/browse/CODETOOLS-7902982): jcstress: Add samples for some mutex algorithms

### Reviewers
 * [Aleksey Shipilev](https://openjdk.java.net/census#shade) (@shipilev - Committer) ⚠️ Review applies to 4ca27a0fc56abd0e565d48b38c2dabf66256698f

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jcstress pull/84/head:pull/84` \
`$ git checkout pull/84`

Update a local copy of the PR: \
`$ git checkout pull/84` \
`$ git pull https://git.openjdk.java.net/jcstress pull/84/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 84`

View PR using the GUI difftool: \
`$ git pr show -t 84`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jcstress/pull/84.diff">https://git.openjdk.java.net/jcstress/pull/84.diff</a>

</details>

### CODE REVIEW

**Comment by shipilev** [comment]
This PR seems to be missing the whole lot of fixes from the previous one. Please transplant the changes here.

**Comment by mmirwaldt** [comment]
> 
> 
> This PR seems to be missing the whole lot of fixes from the previous one. Please transplant the changes here.

Done

**Review by shipilev — APPROVED** [review]

**Comment by mmirwaldt** [comment]
So may I now write a comment with "slash integrate", @shipilev?
I am sorry that I must always ask you but I haven't done such PRs before and I want to avoid confusion and mistakes.
Thanks for your great patience with me!

**Comment by shipilev** [comment]
> So may I now write a comment with "slash integrate", @shipilev? ("slash" will be replaced by the character)
> I am sorry that I must always ask you but I haven't done such PRs before and I want to avoid more confusion and mistakes.
> Thanks for your great patience with me!

Yeah, I think so. Bots complain your Git is probably initialized in some odd way: https://github.com/openjdk/jcstress/pull/84#issuecomment-873022315 -- you might want to take a look at those. Feel free to squash the commits and force-push the result with the new metadata (this one time).

**Pull request closed without merging**
