### PR TITLE
CODETOOLS-7903022: jcstress: Mutex_06_Semaphore sample

### PR DESCRIPTION
**Pull request by mmirwaldt**
I think Mutex_06_Semaphore is missing because many concurrent algorithms use semaphores as mutexes.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Change must be properly reviewed

### Issue
 * [CODETOOLS-7903022](https://bugs.openjdk.java.net/browse/CODETOOLS-7903022): jcstress: Mutex_06_Semaphore sample

### Reviewers
 * [Aleksey Shipilev](https://openjdk.java.net/census#shade) (@shipilev - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jcstress pull/95/head:pull/95` \
`$ git checkout pull/95`

Update a local copy of the PR: \
`$ git checkout pull/95` \
`$ git pull https://git.openjdk.java.net/jcstress pull/95/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 95`

View PR using the GUI difftool: \
`$ git pr show -t 95`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jcstress/pull/95.diff">https://git.openjdk.java.net/jcstress/pull/95.diff</a>

</details>

### CODE REVIEW

**Review by shipilev — APPROVED** [review]
Looks fine.

**Comment by mmirwaldt** [comment]
What's next,@shipilev? Integrate?

**Comment by shipilev** [comment]
> What's next,@shipilev? Integrate?

Yes.

**Comment by shipilev** [comment]
Should be lower-case `/integrate`, I think.

**Pull request closed without merging**
